---
- name: Prepare
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    _java_version:
      default: 11
      Debian-12: 17
    java_version: "{{ _java_version[ansible_distribution_release ~ '-' ~ ansible_distribution_major_version] | default(_java_version['default']) }}"

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.java
    - role: robertdebock.common
