---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: check if port 4440 is available
      wait_for:
        port: 4440

    - name: connect to rundeck
      uri:
        url: "http://localhost:4440/user/login"
        method: GET
