---
- name: Verify
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: check if port 4440 is available
      wait_for:
        port: 4440
        host: "{{ ansible_default_ipv4.address | default('localhost') }}"

    - name: connect to rundeck
      uri:
        url: "http://{{ ansible_default_ipv4.address }}:4440/user/login"
        method: GET
